---
name: 'build-action'
description: 'https://github.com/garethjevans/build-action'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  destination:
    description: 'The full name of the image name to be built'
    required: true
  tag:
    description: 'The tag for the image'
    required: false
    default: 'latest'
  context:
    description: ''
    required: false
    default: '.'
  args:
    description: 'Build arguments to be passed to the underlying kpack or kaniko build process'
    required: false
    default: ''
outputs:
  name:
    description: 'The fully qualified name of the built image including version'
  version:
    description: 'The tag version of the built image'  
runs:
  using: 'docker'
  image: 'docker://garethjevans/build-action:latest'
  entrypoint: 'github-actions-entrypoint.sh'
