---
name: 'build-action'
description: 'https://github.com/garethjevans/build-action'
branding:
  icon: 'tag'
  color: 'blue'
inputs:
  # auth
  server:
    description: 'Address of the server to create the kpack resource'
    required: true
  token:
    description: ''
    required: true
  ca_cert:  
    description: ''
    required: true
  namespace:
    description: 'Name of the developer workspace to perform builds'
    required: true
  # Image configuration  
  destination:
    description: 'The full name of the image name to be built'
    required: true
  context:
    description: ''
    required: false
    default: '.'
  args:
    description: 'Build arguments to be passed to the underlying kpack or kaniko build process'
    required: false
    default: ''
outputs:
  name:
    description: 'The fully qualified name of the built image including version'
  version:
    description: 'The tag version of the built image'  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/garethjevans/build-action:convert-to-golang'
  entrypoint: 'github-actions-entrypoint.sh'
