---
name: test

on:
  pull_request:      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Test
        run: |
          echo $GITHUB_OUTPUT
